### ISSUE TITLE
What start branch?

### ISSUE THREAD

**Issue by seejessicacode** [kentcdodds/react-mocha-workshop#2]
INSTRUCTIONS.md and README mention a start branch, but GitHub says there's no other branch than master.

**Comment by kentcdodds** [comment]
Yeah, sorry about that, I'll get that fixed soon. Thank you for your patience :)

**Comment by kentcdodds** [comment]
I've made a big update. I haven't finished the instructions for setting up the tooling yet, but check the README to see how to implement the tests. Still more work to do, but I'd appreciate any PRs you'd like to make :) [makeapullrequest.com](http://makeapullrequest.com)
